# Generated by Django 5.2.6 on 2025-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_contact_info',
            field=models.BooleanField(default=True, help_text='Show my contact information to other users'),
        ),
    ]
