# Generated by Django 5.2.6 on 2025-09-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('HB_Town', 'Homa Bay Town'), ('Kendu_Bay', 'Kendu Bay'), ('Rodi_Kopany', 'Rodi Kopany'), ('Mbita', 'Mbita'), ('Oyugis', 'Oyugis'), ('Rangwe', 'Rangwe'), ('Ndhiwa', 'Ndhiwa'), ('Suba', 'Suba')], max_length=50)),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('is_sold', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.category')),
            ],
        ),
    ]
