# Generated by Django 5.2.6 on 2025-09-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='listings.listing'),
        ),
    ]
