# Generated by Django 4.2.7 on 2025-09-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_condition_listing_delivery_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='listing_images/default.png', upload_to='listing_images/'),
        ),
    ]
