# Generated by Django 4.2.7 on 2025-09-25 07:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=cloudinary.models.CloudinaryField(default='listing_images/default.png', max_length=255, verbose_name='image'),
        ),
    ]
