# Generated by Django 5.2.6 on 2025-10-24 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_escrow_auto_release_date_escrow_dispute_resolved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Skip database operations entirely - assume table exists
            database_operations=[],
            # Update Django's state to know about the field
            state_operations=[
                migrations.AddField(
                    model_name='listing',
                    name='favorited_by',
                    field=models.ManyToManyField(blank=True, related_name='favorited_listings', to=settings.AUTH_USER_MODEL),
                ),
            ]
        ),
    ]
