# Generated by Django 5.2.6 on 2025-10-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listing_favorited_by'),
        ('storefront', '0002_subscription_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='storefront.store'),
        ),
    ]
