# Generated by Django 5.2.6 on 2025-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_add_mpesa_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('trialing', 'Trial Period')], default='trialing', max_length=20),
        ),
    ]
