# Generated by Django 5.2.6 on 2025-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_covers/'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
